import { createReadStream, writeFileSync } from "fs";
import rl from "readline";
import { Board, Move, Zobrist } from "../src/index.js";

const input = createReadStream("book.txt", "utf8");

const reader = rl.createInterface({ input });

const book: Record<string, number[]> = {};

for await (const line of reader) {
    const board = new Board().loadStartingPosition();

    const unparsed = line.split(" ").slice(0, -1); // trim off scoring

    const game: Move[] = [];

    for (const move of unparsed) {
        const parsed = Move.parseAlgebraicNotation(move, board);

        const key = board.zobristKey.toString();

        if (!(key in book)) book[key] = [];

        if (!book[key].includes(parsed.bits)) book[key].push(parsed.bits);

        board.makeMove(parsed);

        game.push(parsed);
    }
}

writeFileSync("src/ZobristBookValues.ts", `\
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.

/**
 * precomputed zobrist values used to generate the opening book
 * autogenerated by tests/parse_book.ts
 */
const ZobristBookValues = {
    piecesArray: [${Zobrist.piecesArray.map((sides) => `[${sides.map((ints) => `[${ints.map((x) => `0x${x.toString(16)}n`).join(", ")}]`).join(", ")}]`).join(", ")}],
    castlingRights: [${Zobrist.castlingRights.map((x) => `0x${x.toString(16)}n`).join(", ")}],
    enPassantFile: [${Zobrist.enPassantFile.map((x) => `0x${x.toString(16)}n`).join(", ")}],
    sideToMove: 0x${Zobrist.sideToMove.toString(16)}n,
};

export default ZobristBookValues;
`, "utf8");

writeFileSync("src/book/book.ts", `\
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.

/**
 * this is the engine's opening book
 * autogenerated by tests/parse_book.ts
 */
const OpeningBook: Record<string, number[]> = {
${Object.entries(book).map(([zobristKey, moveValues]) => `    ["${zobristKey}"]: [${moveValues.map((x) => `0x${x.toString(16)}`).join(", ")}],`).join("\n")}
};

export default OpeningBook;
`, "utf8");
